TransbankDevelopers/transbank-sdk-python

tests/onepay/test_transaction.py, transbank/onepay/schema.py, transbank/onepay/transaction.py
This PR includes the implementation of Transaction.commit, and their tests.
=> Transaction.commit

tests/onepay/test_refund.py, tests/onepay/test_transaction.py, transbank/onepay/__init__.py, transbank/onepay/transaction.py
This PR set TEST as the default environment, with their default credentials.
=> Set TEST as default environment

CHANGELOG.md
First version of Transbank SDK, which contains functionalities to implement Onepay.
=> Prepare Release v1.0.0

transbank/onepay/__init__.py, transbank/onepay/schema.py, transbank/onepay/transaction.py
Add support for commerce logo and qr width-height parameters.
=> Add support for commerce logo and qr width height

.github/ISSUE_TEMPLATE/reporte-de-error.md
=> Add bug issue templates

transbank/patpass_by_webpay/transaction.py, transbank/webpay/webpay_plus/schema.py
Add status method for Patpass By Webpay
=> Implement status method for Patpass By Webpay

transbank/webpay/webpay_plus/request/__init__.py, transbank/webpay/webpay_plus/response/__init__.py, transbank/webpay/webpay_plus/schema.py, transbank/webpay/webpay_plus/transaction.py
Add refund method on Webpay Plus
=> Implement refund method on Webpay Plus

transbank/webpay/webpay_plus/mall_transaction.py, transbank/webpay/webpay_plus/response/__init__.py, transbank/webpay/webpay_plus/schema.py
Add method commit for Webpay Plus Mall
=> Implement commit method for Webpay Plus Mall

CHANGELOG.md, transbank/__version__.py
Prepare release 1.3.0
Fill diff: https://github.com/TransbankDevelopers/transbank-sdk-python/compare/v1.2.1...chore/prepare-release-1.3.0
=> Prepare release 1.3.0

transbank/webpay/webpay_plus/response/__init__.py
Onepay wasn't working because VCI wasn't optional
=> Fix optional fields

tests/webpay/plus/test_transaction.py, transbank/webpay/webpay_plus/__init__.py, transbank/webpay/webpay_plus/response/__init__.py, transbank/webpay/webpay_plus/transaction.py
=> Add Webpay plus configuration

CHANGELOG.md, transbank/__version__.py
Several fixes.
Full diff [here](https://github.com/TransbankDevelopers/transbank-sdk-python/compare/v1.3.0...chore/prepare-release-1.4.0)
=> Prepare release 1.4.0

CHANGELOG.md, transbank/__version__.py
Full diff https://github.com/TransbankDevelopers/transbank-sdk-python/compare/1.4.0...master
=> Prepare release 1.5.0

CHANGELOG.md, README.md, transbank/__version__.py
Full diff https://github.com/TransbankDevelopers/transbank-sdk-python/compare/2.0.1...master
=> add 3.0.0 changelog

.travis.yml, Pipfile, Pipfile.lock, setup.py, transbank/patpass_by_webpay/transaction.py, transbank/patpass_comercio/inscription.py, transbank/webpay/oneclick/mall_inscription.py, transbank/webpay/oneclick/mall_transaction.py, transbank/webpay/transaccion_completa/mall_transaction.py, transbank/webpay/transaccion_completa/transaction.py, transbank/webpay/webpay_plus/mall_transaction.py, transbank/webpay/webpay_plus/transaction.py, transbank/webpay/webpay_plus_modal/transaction.py
Updated call to Schema.dumps() in marshmallow v3
=> Updated to marshmallow v3

tests/mocks/responses_api_mocks.py, tests/webpay/oneclick/test_mall_inscription.py, tests/webpay/oneclick/test_mall_transaction.py, tests/webpay/plus/test_transaction.py, tests/webpay/test_utils.py
=> test: add oneclick mall test

.travis.yml
Use java 17 to execute SonarClouds checks
Test
=> chore: use java 17 to execute sonar cloud

.travis.yml, CHANGELOG.md, transbank/__version__.py, transbank/common/api_constants.py, transbank/common/request_service.py, transbank/webpay/oneclick/mall_inscription.py, transbank/webpay/transaccion_completa/transaction.py
Full diff: https://github.com/TransbankDevelopers/transbank-sdk-python/compare/master...chore/prepare-release-5.0.0
=> chore: prepare release 5.0.0

.travis.yml
This PR adjusts the Travis Machine version
=> chore: adjust travis machine version

.travis.yml
This PR sets the machine distribution `focal` on the Travis CI/CD
=> chore: set focal version for travis machine

transbank/common/options.py, transbank/common/request_service.py
This version includes the following changes:
- Add default timeout of 10 minutes in options.
- Add custom timeout in options.
- Timeout configuration in RequestService.cs
> Case with 10 second (custom timeout)
> Case with 60 second (default Timeout)
=> feat: add request timeout

Pipfile, Pipfile.lock, README.md, setup.py
=> chore: update libraries

Pipfile, Pipfile.lock, setup.py
This PR update outdated dependencies
=> chore: update dependencies

.github/workflows/publish.yml
This PR fix actions folder name
=> chore: fix actions folder name

.github/workflows/publish.yml
=> chore: use pipenv on publish action

.github/workflows/publish.yml
this pr removes use of pip cache on publish action
=> chore: remove pip cache

.github/workflows/publish.yml
remove cache flag from publish file
=> chore: delete cache

sonar-project.properties
This PR add the coverage PATH in sonar ci flow
=> chore: add coverage path in sonar ci flow

.github/workflows/sonar.yml
This PR update the trigger for sonar flow ci.
=> chore: update trigger for sonar flow ci
